# Generated by Django 5.2.15 on 2026-06-11 06:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Broker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="中介/渠道"
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="联系方式"
                    ),
                ),
                (
                    "fast_pay_commission",
                    models.BooleanField(default=False, verbose_name="佣金快速支付"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "中介",
                "verbose_name_plural": "中介",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Charge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("income", "应收"), ("expense", "应付")],
                        max_length=10,
                        verbose_name="方向",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("rent", "房租"),
                            ("deposit", "押金"),
                            ("heating", "取暖费"),
                            ("commission", "中介佣金"),
                            ("wage", "工资"),
                            ("property_rent", "产权方租金"),
                            ("repair", "维修"),
                            ("utility", "水电等费用"),
                            ("move_diff", "换房补差"),
                            ("deposit_refund", "押金退款"),
                            ("other", "其他"),
                        ],
                        max_length=30,
                        verbose_name="类别",
                    ),
                ),
                ("due_date", models.DateField(verbose_name="应收/应付日期")),
                (
                    "period_start",
                    models.DateField(blank=True, null=True, verbose_name="周期开始"),
                ),
                (
                    "period_end",
                    models.DateField(blank=True, null=True, verbose_name="周期结束"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="金额",
                    ),
                ),
                ("description", models.CharField(max_length=200, verbose_name="说明")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "待处理"),
                            ("partial", "部分处理"),
                            ("paid", "已结清"),
                            ("void", "已作废"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("auto", "系统生成"),
                            ("manual", "手动录入"),
                            ("adjustment", "调整生成"),
                            ("opening", "期初导入"),
                        ],
                        default="auto",
                        max_length=20,
                        verbose_name="来源",
                    ),
                ),
                (
                    "generated_key",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        unique=True,
                        verbose_name="生成键",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "账单",
                "verbose_name_plural": "账单",
                "ordering": ["due_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("income", "应收"), ("expense", "应付")],
                        max_length=10,
                        verbose_name="方向",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="日期"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="金额",
                    ),
                ),
                (
                    "method",
                    models.CharField(blank=True, max_length=60, verbose_name="方式"),
                ),
                (
                    "memo",
                    models.CharField(blank=True, max_length=240, verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "收付款",
                "verbose_name_plural": "收付款",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="姓名")),
                (
                    "id_number",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="身份证号"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=40, verbose_name="手机号"),
                ),
                (
                    "emergency_name",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="紧急联系人"
                    ),
                ),
                (
                    "emergency_phone",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="紧急联系人电话"
                    ),
                ),
                (
                    "emergency_address",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="紧急联系人地址"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "人员",
                "verbose_name_plural": "人员",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RecurringRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                (
                    "direction",
                    models.CharField(
                        choices=[("income", "应收"), ("expense", "应付")],
                        default="expense",
                        max_length=10,
                        verbose_name="方向",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("rent", "房租"),
                            ("deposit", "押金"),
                            ("heating", "取暖费"),
                            ("commission", "中介佣金"),
                            ("wage", "工资"),
                            ("property_rent", "产权方租金"),
                            ("repair", "维修"),
                            ("utility", "水电等费用"),
                            ("move_diff", "换房补差"),
                            ("deposit_refund", "押金退款"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=30,
                        verbose_name="类别",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="金额"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "每月"),
                            ("quarterly", "每季度"),
                            ("yearly", "每年"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="频率",
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="每月几日"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="开始日期")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="结束日期"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="启用")),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "周期规则",
                "verbose_name_plural": "周期规则",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=20, unique=True, verbose_name="房间号"),
                ),
                (
                    "area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="面积",
                    ),
                ),
                (
                    "orientation",
                    models.CharField(blank=True, max_length=30, verbose_name="朝向"),
                ),
                (
                    "floor",
                    models.CharField(blank=True, max_length=30, verbose_name="楼层"),
                ),
                (
                    "listing_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="挂牌价",
                    ),
                ),
                (
                    "commission_base",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2000.00"),
                        max_digits=10,
                        verbose_name="默认佣金",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("vacant", "空房"),
                            ("occupied", "在住"),
                            ("expiring", "合同即将到期"),
                            ("self_use", "自用"),
                            ("maintenance", "维修中"),
                        ],
                        default="vacant",
                        max_length=20,
                        verbose_name="房态",
                    ),
                ),
                (
                    "room_password",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="房间密码"
                    ),
                ),
                (
                    "qr_code_url",
                    models.URLField(blank=True, verbose_name="自主申报二维码"),
                ),
                (
                    "water_fee",
                    models.CharField(
                        default="9.5/吨", max_length=80, verbose_name="水费"
                    ),
                ),
                (
                    "electricity_fee",
                    models.CharField(
                        default="1.4/度", max_length=80, verbose_name="电费"
                    ),
                ),
                (
                    "property_fee",
                    models.CharField(
                        default="免", max_length=80, verbose_name="物业费"
                    ),
                ),
                (
                    "internet_fee",
                    models.CharField(default="免", max_length=80, verbose_name="网费"),
                ),
                (
                    "heating_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("380.00"),
                        max_digits=8,
                        verbose_name="取暖费/月",
                    ),
                ),
                (
                    "parking_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("150.00"),
                        max_digits=8,
                        verbose_name="停车费/月",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "房间",
                "verbose_name_plural": "房间",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Allocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="核销金额",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "charge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="core.charge",
                        verbose_name="账单",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="core.payment",
                        verbose_name="收付款",
                    ),
                ),
            ],
            options={
                "verbose_name": "核销",
                "verbose_name_plural": "核销",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="core.person",
                verbose_name="人员",
            ),
        ),
        migrations.AddField(
            model_name="charge",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="charges",
                to="core.person",
                verbose_name="人员",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="core.room",
                verbose_name="房间",
            ),
        ),
        migrations.AddField(
            model_name="charge",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="charges",
                to="core.room",
                verbose_name="房间",
            ),
        ),
        migrations.CreateModel(
            name="Tenancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="合同开始日期")),
                ("end_date", models.DateField(verbose_name="合同结束日期")),
                (
                    "move_out_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="实际退租日期"
                    ),
                ),
                (
                    "monthly_rent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="月租金",
                    ),
                ),
                (
                    "payment_cycle",
                    models.CharField(
                        choices=[
                            ("monthly", "月付"),
                            ("quarterly", "季付"),
                            ("half_year", "半年付"),
                            ("yearly", "年付"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="付款周期",
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("3500.00"),
                        max_digits=10,
                        verbose_name="押金",
                    ),
                ),
                (
                    "commission_base",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2000.00"),
                        max_digits=10,
                        verbose_name="佣金基数",
                    ),
                ),
                (
                    "commission_manual_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="佣金手动金额",
                    ),
                ),
                (
                    "commission_due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="佣金应付日期"
                    ),
                ),
                (
                    "commission_paid_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="佣金实付日期"
                    ),
                ),
                (
                    "police_report_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="报备展示结束日期"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "未入住"),
                            ("active", "在租"),
                            ("ended", "已退租"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "broker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenancies",
                        to="core.broker",
                        verbose_name="中介",
                    ),
                ),
                (
                    "primary_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_tenancies",
                        to="core.person",
                        verbose_name="主租客",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenancies",
                        to="core.room",
                        verbose_name="房间",
                    ),
                ),
            ],
            options={
                "verbose_name": "合同",
                "verbose_name_plural": "合同",
                "ordering": ["-start_date", "room__number"],
            },
        ),
        migrations.CreateModel(
            name="Stay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stay_type",
                    models.CharField(
                        choices=[("permanent", "常住"), ("visitor", "探望/暂住")],
                        default="permanent",
                        max_length=20,
                        verbose_name="入住类型",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="入住开始日期")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="入住结束日期"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="当前在住"),
                ),
                (
                    "report_note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="报备备注"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stays",
                        to="core.person",
                        verbose_name="人员",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stays",
                        to="core.room",
                        verbose_name="房间",
                    ),
                ),
                (
                    "tenancy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stays",
                        to="core.tenancy",
                        verbose_name="合同",
                    ),
                ),
            ],
            options={
                "verbose_name": "入住记录",
                "verbose_name_plural": "入住记录",
                "ordering": ["room__number", "person__name"],
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="tenancy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="core.tenancy",
                verbose_name="合同",
            ),
        ),
        migrations.AddField(
            model_name="charge",
            name="tenancy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="charges",
                to="core.tenancy",
                verbose_name="合同",
            ),
        ),
        migrations.CreateModel(
            name="Adjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[
                            ("discount", "优惠/减免"),
                            ("manual_override", "手动改价"),
                            ("move_diff", "换房补差"),
                            ("deposit_deduction", "押金扣款"),
                            ("other", "其他调整"),
                        ],
                        max_length=30,
                        verbose_name="类型",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="生效日期"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="金额",
                    ),
                ),
                ("description", models.CharField(max_length=240, verbose_name="说明")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "charge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="core.charge",
                        verbose_name="账单",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adjustments",
                        to="core.person",
                        verbose_name="人员",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adjustments",
                        to="core.room",
                        verbose_name="房间",
                    ),
                ),
                (
                    "tenancy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="core.tenancy",
                        verbose_name="合同",
                    ),
                ),
            ],
            options={
                "verbose_name": "调整",
                "verbose_name_plural": "调整",
                "ordering": ["-effective_date", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="charge",
            index=models.Index(
                fields=["direction", "status", "due_date"],
                name="core_charge_directi_a22694_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="charge",
            index=models.Index(
                fields=["category", "due_date"], name="core_charge_categor_a87a9d_idx"
            ),
        ),
    ]
