# Generated by Django 5.2.15 on 2026-06-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenancy",
            name="billing_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="系统计费起始日期"
            ),
        ),
    ]
