# Generated by Django 5.2.15 on 2026-06-11 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_tenancy_billing_start_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="broker",
            name="fast_pay_commission",
        ),
    ]
