# Generated by Django 5.2.15 on 2026-06-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_broker_fast_pay_commission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="direction",
            field=models.CharField(
                choices=[("receive", "收"), ("pay", "付")],
                max_length=10,
                verbose_name="方向",
            ),
        ),
        migrations.AlterField(
            model_name="stay",
            name="stay_type",
            field=models.CharField(
                choices=[
                    ("permanent", "常住"),
                    ("visitor", "探望/暂住"),
                    ("manager", "管理员"),
                ],
                default="permanent",
                max_length=20,
                verbose_name="入住类型",
            ),
        ),
    ]
