# Generated by Django 5.2.15 on 2026-06-11 09:18

from django.db import migrations, models


def normalize_floor_values(apps, schema_editor):
    Room = apps.get_model("core", "Room")
    first_values = {"1层", "一层", "1楼", "一楼", "1"}
    for room in Room.objects.all():
        floor = (room.floor or "").strip()
        room.floor = "1层" if floor in first_values else "2层"
        room.save(update_fields=["floor"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_payment_direction_alter_stay_stay_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="category",
            field=models.CharField(
                choices=[("deposit", "押金"), ("rent", "租金"), ("other", "其它")],
                default="other",
                max_length=20,
                verbose_name="款项类型",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="qr_code_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="room_qr_codes/",
                verbose_name="自主申报二维码图片",
            ),
        ),
        migrations.RunPython(normalize_floor_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="room",
            name="floor",
            field=models.CharField(
                choices=[("1层", "1层"), ("2层", "2层")],
                default="2层",
                max_length=30,
                verbose_name="楼层",
            ),
        ),
    ]
