# Generated by Django 5.2.15 on 2026-06-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_payment_category_room_qr_code_image_alter_room_floor"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenancy",
            name="planned_deposit_refund_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="预计退还押金",
            ),
        ),
        migrations.AddField(
            model_name="tenancy",
            name="planned_move_out_date",
            field=models.DateField(blank=True, null=True, verbose_name="预计退租日期"),
        ),
        migrations.AddField(
            model_name="tenancy",
            name="planned_move_out_note",
            field=models.TextField(blank=True, verbose_name="预计退租备注"),
        ),
    ]
