# Generated by Django 5.2.17 on 2026-09-30 08:25

import django.db.models.deletion
from django.db import migrations, models


def keep_existing_expenses_independent(apps, schema_editor):
    # Keep all existing allocations; only stop unused expense amounts matching new bills.
    Payment = apps.get_model('core', 'Payment')
    Payment.objects.filter(direction='pay').update(auto_allocate=False)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tenancy_planned_deposit_refund_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_defaults', models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='auto_allocate',
            field=models.BooleanField(default=True, verbose_name='自动抵扣'),
        ),
        migrations.AddField(
            model_name='tenancy',
            name='previous_tenancy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renewal', to='core.tenancy', verbose_name='续租前合同'),
        ),
        migrations.RunPython(keep_existing_expenses_independent, migrations.RunPython.noop),
    ]
