# Generated by Django 5.2.17 on 2026-09-30 09:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_apartmentsettings_payment_auto_allocate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenancy',
            name='billing_enabled',
            field=models.BooleanField(default=True, help_text='导入资料待补时关闭；确认押金、期初账务及计费起点后启用。', verbose_name='启用自动计费'),
        ),
        migrations.AlterField(
            model_name='person',
            name='id_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('3500.00'), max_digits=10, null=True, verbose_name='押金'),
        ),
    ]
