# Generated by Django 5.2.17 on 2026-10-02 03:40

from django.db import migrations, models
from uuid import uuid4


def queue_unconfirmed_departures(apps, schema_editor):
    """No server-side sending history exists; report prior departures once."""
    alias = schema_editor.connection.alias if schema_editor else "default"
    Stay = apps.get_model("core", "Stay")
    successors = set(Stay.objects.using(alias).filter(tenancy__previous_tenancy__isnull=False).values_list(
        "tenancy__previous_tenancy_id", "person_id"))
    for stay in Stay.objects.using(alias).filter(is_active=False, police_departure_token__isnull=True).select_related("tenancy"):
        if (stay.tenancy_id, stay.person_id) in successors and not stay.tenancy.move_out_date:
            continue
        Stay.objects.using(alias).filter(pk=stay.pk).update(police_departure_token=uuid4())


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_yueshan_rules"),
    ]

    operations = [
        migrations.CreateModel(
            name="PoliceReportExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="报备日期")),
                ("rows", models.JSONField(default=list, verbose_name="报备人员快照")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="生成时间"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发送确认时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "警务报备记录",
                "verbose_name_plural": "警务报备记录",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="stay",
            name="police_departure_reported_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="离开报备确认时间"
            ),
        ),
        migrations.AddField(
            model_name="stay",
            name="police_departure_token",
            field=models.UUIDField(
                blank=True, editable=False, null=True, verbose_name="本次离开报备标识"
            ),
        ),
        migrations.RunPython(queue_unconfirmed_departures, migrations.RunPython.noop),
    ]
