# Generated by Django 5.2.17 on 2026-10-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_police_departure_reporting"),
    ]

    operations = [
        migrations.AddField(
            model_name="stay",
            name="police_departure_required",
            field=models.BooleanField(default=True, verbose_name="退租是否报备"),
        ),
        migrations.AddField(
            model_name="stay",
            name="police_report_text_override",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="手动报备内容"
            ),
        ),
    ]
