# Generated by Django 5.2.15 on 2026-10-05 08:08

from django.db import migrations, models


def preserve_current_fees(apps, schema_editor):
    Tenancy = apps.get_model("core", "Tenancy")
    names = ("water_fee", "electricity_fee", "heating_fee", "property_fee", "internet_fee", "parking_fee")
    for tenancy in Tenancy.objects.using(schema_editor.connection.alias).select_related("room").iterator():
        tenancy.fee_terms = {name: str(getattr(tenancy.room, name)) for name in names}
        tenancy.save(update_fields=["fee_terms"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_police_report_manual_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="charge",
            name="entry_token",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="entry_token",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="tenancy",
            name="fee_terms",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="合同费用约定"
            ),
        ),
        migrations.RunPython(preserve_current_fees, migrations.RunPython.noop),
    ]
